Function read3D created
ruttam/BalanceRobot pull request #1
Opened 2016-11-25 08:17 UTC by ruttam

Check if it is valid.

read3D function is not fully completed yet.

2016-11-25 08:52 UTC, Amosejevas requested changes
Reviewed. Please adjust change according to review comments.

2016-11-25 08:52 UTC, Amosejevas commented on balanceRobot.ino
> +void read3D {
Naming is not clear, please change the function name to `readAccelerometerData()` or something like that.

2016-11-25 08:52 UTC, Amosejevas commented on balanceRobot.ino
> +    Serial.print("Accelerometer: ");
Is there a way to print all data in one line? `Serial.printf(F("Value: %3d\n"), value);`.

2016-11-25 08:52 UTC, Amosejevas commented on balanceRobot.ino
>      if(state[1] == 97)
Please use curly braces, now it''s not clear what is this statement used for.

2016-11-25 08:52 UTC, Amosejevas commented on balanceRobot.ino
> +    if(x < -1.1 && x > -5) {
Please add a comment explaining what each branch is for.

2016-11-29 22:41 UTC, ruttam commented on balanceRobot.ino
>      if(state[1] == 97)
Done.

2016-11-29 22:54 UTC, ruttam commented on balanceRobot.ino
> +    if(x < -1.1 && x > -5) {
Done.

2016-11-29 22:56 UTC, ruttam commented on balanceRobot.ino
> +void read3D {
Done.

2016-11-29 23:00 UTC, ruttam commented on balanceRobot.ino
> +    Serial.print("Accelerometer: ");
Since we are not going to use y and z axis, I removed them and changed the printing of the x value.

2016-12-01 19:45 UTC, Amosejevas commented on balanceRobot.ino
> +    Serial.print("Accelerometer: ");
That's a great decision. I am waiting forward to see the changes. Please update pull request and  It will reviewed.

2016-12-03 16:05 UTC, merged